#pragma once
void menu();
void manualOperation();
int main();
void readBatteryStats(); 
void coordinateInput();
void clrscr();
void serialWrite();
char serialRead();
void serialInit();
void getComPort();
void anyKey();